project:
  type: website
  output-dir: docs

website:
  site-url: https://giorgistat.github.io/
  title: "Welcome to My Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: books.qmd
        text: Books
      - text: Publications
        menu:
          - href: publications/index.qmd
            text: Overview
          - href: publications/original-research.qmd
            text: Original Research
          - href: publications/book-chapters.qmd
            text: Book Chapters
          - href: publications/other-publications.qmd
            text: Other Publications


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    head-includes:
    - |
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-4LTGE2N1P2"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-4LTGE2N1P2');
      </script>

editor: visual
