project:
  type: website
  output-dir: docs

website:
  site-url: https://giorgistat.github.io/
  title: "Welcome to My Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: books.qmd
        text: Books
      - text: Projects
        href: projects/index.qmd
      - text: Publications
        menu:
          - href: publications/index.qmd
            text: Overview
          - href: publications/original-research.qmd
            text: Original Research
          - href: publications/book-chapters.qmd
            text: Book Chapters
          - href: publications/other-publications.qmd
            text: Other Publications
      - href: talks/index.qmd
        text: Talks
      - href: teaching/index.qmd
        text: Teaching

  # About card under profile picture
  page-footer: ""

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

# About section for profile sidebar (add this to index.qmd or _quarto.yml if shared globally)
about:
  template: trestles
  image: profile.jpg
  image-width: 15em
  image-shape: round
  links:
    - icon: envelope
      text: "e.giorgi@lancaster.ac.uk"
      href: "mailto:e.giorgi@lancaster.ac.uk"
    - text: "<img src='bs.png' alt='Bluesky' style='height:1em; vertical-align:middle;'> @giorgistat.bsky.social"
      href: "https://bsky.app/profile/giorgistat.bsky.social"
