project:
  type: website
  output-dir: docs

website:
  site-url: https://egiorgi.github.io
  title: "Don't let appearances fool you"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: books.qmd
        text: Books
      - text: Publications
        menu:
          - href: publications/index.qmd
            text: Overview
          - href: publications/original-research.qmd
            text: Original Research
          - href: publications/book-chapters.qmd
            text: Book Chapters
          - href: publications/other-publications.qmd
            text: Other Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
